import { Project, GalleryItem } from "./types";

export const PROJECTS: Project[] = [
  {
    id: "graduation",
    title: "Batch '26 Graduation Ceremony",
    titleAr: "حفل تخرج دفعة 2026",
    client: "Arab Open University",
    clientAr: "الجامعة العربية المفتوحة",
    year: "2026",
    role: "Lead Graphic Designer",
    roleAr: "المصمم الرئيسي للهوية البصرية",
    duration: "2 Months",
    durationAr: "شهران",
    coverImage: "/assets/graduation/Batch  Graduation Ceremony.jpg",
    brief: "The graduation ceremony for AOU's 26th class was held across three cities on the same occasion, with attendance from members of the royal family and regional princes. The university set the core colors and logo; my task was to build a fuller visual identity around them — one substantial enough for the scale and stature of the event, while staying consistent across three separate venues and their individual constraints.",
    briefAr: "أُقيم حفل تخرج الدفعة السادسة والعشرين للجامعة العربية المفتوحة في ثلاث مدن رئيسية (الرياض، جدة، والدمام) بالتزامن، بتشريف كريم من أصحاب السمو الملكي وأمراء المناطق. حددت الجامعة الألوان الأساسية والشعار؛ وكانت مهمتي هي بناء هوية بصرية متكاملة وشاملة تتناسب مع حجم ومكانة هذا الحدث الوطني المهيب، مع الحفاظ على الاتساق البصري عبر ثلاثة مواقع مختلفة وبظروفها اللوجستية الخاصة.",
    approach: "This was my first project at this scale — my first time designing across three cities simultaneously. Rather than treating each city as a separate job, I built one cohesive visual language and adapted it city by city where the venue required it, keeping the identity recognizable everywhere while respecting each space's own layout and needs.",
    approachAr: "كان هذا مشروعي الأول بهذا الحجم الضخم، وتجربتي الأولى في التصميم بالتوازي لثلاث مدن مختلفة. بدلاً من التعامل مع كل مدينة كعمل منفصل، قمت ببناء لغة بصرية موحدة ومتماسكة، ثم تكييفها وتطويعها لمتطلبات وقاعات كل مدينة، مما حافظ على وحدة الهوية البصرية وتميزها مع احترام الخصوصية المعمارية والمساحية لكل موقع.",
    outcome: "The identity was delivered consistently across all three cities for a graduating class of roughly 5,100 students of diverse nationalities and ages — the largest and most demanding project I'd led at that point, completed over two months to meet the standard the occasion called for.",
    outcomeAr: "تم تسليم وتطبيق الهوية البصرية بنجاح وبأعلى معايير الدقة والاتساق في المدن الثلاث لدفعة تضم حوالي 5,100 خريج وخريجة من مختلف الجنسيات والأعمار. كان هذا المشروع الأكبر والأكثر تحدياً في مسيرتي حينها، وتطلب شهرين من العمل المتواصل والدؤوب ليرتقي للمستوى الرفيع الذي تقتضيه المناسبة.",
    tools: ["Affinity Designer", "Affinity Publisher", "Canva"],
    deliverables: [
      "Invitation design",
      "Event agenda",
      "Stage backdrop",
      "Graduate certificates",
      "Signage & banners",
      "Social announcements",
      "Screen / LCD graphics",
      "Entrance gate",
      "Logo photo mural",
      "Graduation photo mural",
      "Ceremony cubes",
      "Directional signage",
      "Flags",
      "Presentation deck"
    ],
    deliverablesAr: [
      "تصميم بطاقات الدعوة",
      "جدول أعمال الحفل",
      "خلفية المسرح الرئيسي",
      "شهادات الخريجين",
      "اللوحات واللافتات الإعلانية",
      "إعلانات شبكات التواصل",
      "تصاميم الشاشات والـ LCD",
      "بوابة المدخل الرئيسية",
      "جدارية الصور الفلكس بالشعار",
      "جدارية صور الخريجين",
      "مكعبات الهوية المضيئة",
      "اللوحات الإرشادية والاتجاهات",
      "أعلام الفعالية الخارجية",
      "العرض التقديمي الرئيسي"
    ],
    stats: [
      { value: "3", valueAr: "٣", label: "Cities Served", labelAr: "مدن مغطاة" },
      { value: "5,100", valueAr: "٥,١٠٠", label: "Graduates", labelAr: "خريج وخريجة" },
      { value: "2 Mo.", valueAr: "شهرين", label: "Production", labelAr: "مدة الإنتاج" },
      { value: "Affinity", valueAr: "أفينيتي", label: "Primary Tool", labelAr: "الأداة الرئيسية" }
    ],
    images: [
      { src: "/assets/graduation/Event flags outside the venue.jpg", alt: "Event flags outside the venue", altAr: "أعلام الحفل ترفرف خارج مقر الفعالية" },
      { src: "/assets/graduation/cubes.jpg", alt: "Ceremony cubes, lobby", altAr: "مكعبات الحفل المضيئة في صالة الاستقبال" },
      { src: "/assets/graduation/Entrance gate arch (2).jpg", alt: "Entrance gate arch", altAr: "قوس بوابة الدخول الرئيسية المصممة بهوية الحفل" },
      { src: "/assets/graduation/Directional wayfinding signage, lobby.png", alt: "Directional wayfinding signage, lobby", altAr: "اللوحات الإرشادية وتوجيه المسارات بصالة الاستقبال" }
    ],
    nextProjectId: "forum",
    prevProjectId: "wincom"
  },
  {
    id: "forum",
    title: "Annual Scientific Research Forum",
    titleAr: "الملتقى السنوي للبحث العلمي",
    client: "Arab Open University",
    clientAr: "الجامعة العربية المفتوحة",
    year: "2026",
    role: "Lead Visual Identity Designer",
    roleAr: "مصمم الهوية البصرية الرئيسي",
    duration: "1.5 Months",
    durationAr: "شهر ونصف",
    coverImage: "/assets/forum/D1106320.jpg",
    brief: "AOU organized its 2026 Annual Scientific Research Forum under the theme 'Scientific Research and Collaborative Intelligence: Evaluating Challenges and Envisioning the Future' — aimed at promoting innovation and building cooperation among researchers. As the host is a university and the event technical in nature, the identity needed to bridge academia and technology visually.",
    briefAr: "نظمت الجامعة العربية المفتوحة ملتقاها السنوي للبحث العلمي لعام 2026 تحت شعار 'البحث العلمي والذكاء التشاركي: تقييم التحديات واستشراف المستقبل'، لتعزيز الابتكار والتعاون البحثي. وبما أن الجهة المنظمة هي صرح أكاديمي والحدث ذو طبيعة تقنية عميقة، فقد تطلب ذلك هوية بصرية متميزة تجسر المسافة بصرياً بين رصانة الأكاديميا وديناميكية التكنولوجيا الحديثة.",
    approach: "The identity was developed from the forum's own logo outward — starting with sketches and progressing to a final visual system that felt both scholarly and technical, carried consistently across every touchpoint of the day.",
    approachAr: "تم تطوير الهوية البصرية من فلسفة وشكل شعار الملتقى نفسه، مروراً بمراحل التخطيط والرسم الأولي (Sketches)، ووصولاً إلى بناء نظام بصري متكامل يجمع بين الرصانة البحثية والدقة التقنية، وتطبيقه باتساق تام عبر كافة نقاط الاتصال والمطبوعات على مدار اليوم.",
    outcome: "A cohesive identity spanning stage, print, and digital touchpoints for the university's flagship research event — carried through from the opening invitation to the student project exhibition.",
    outcomeAr: "إنتاج هوية بصرية متماسكة ومتناسقة امتدت لتغطي خشبة المسرح، والمطبوعات الإدارية، والشاشات الرقمية للفعالية الأبرز بالجامعة، مرافقة للحضور من بطاقة الدعوة الأولى وحتى أجنحة معرض بحوث الطلاب المشترك.",
    tools: ["Affinity Designer", "Canva", "Adobe InDesign"],
    deliverables: [
      "Invitations",
      "Agenda",
      "Stage stands",
      "Presentation deck",
      "Theatre LCD screen",
      "Badges",
      "Entrance gate",
      "Event LCD cubes",
      "Workshop banners",
      "Certificates",
      "Winners' checks",
      "Exhibition banners"
    ],
    deliverablesAr: [
      "بطاقات الدعوة الرقمية والورقية",
      "كتيب جدول الأعمال والبرنامج",
      "منصات وحوامل المسرح",
      "العرض التقديمي الرئيسي للملتقى",
      "خلفية مسرح القاعة الرئيسية (LCD)",
      "بطاقات تعريف الحضور والمنظمين",
      "بوابة الدخول للملتقى",
      "مكعبات وشاشات العرض المضيئة",
      "لوحات ورش العمل الجانبية",
      "شهادات التكريم والمشاركة",
      "شيكات الفائزين بالجوائز البحثية",
      "لوحات وملصقات معرض مشاريع الطلاب"
    ],
    stats: [
      { value: "1 Day", valueAr: "يوم واحد", label: "Forum Duration", labelAr: "مدة الملتقى" },
      { value: "12", valueAr: "١٢", label: "Deliverable Types", labelAr: "أنواع المخرجات" },
      { value: "10", valueAr: "١٠", label: "Photographed Pieces", labelAr: "قطع مصورة ميدانياً" },
      { value: "Solo", valueAr: "منفرد", label: "Design Lead", labelAr: "قيادة التصميم" }
    ],
    images: [
      { src: "/assets/forum/الدعوة (2).png", alt: "Digital and print invitation card", altAr: "تصميم بطاقة الدعوة والمطبوعات الإعلانية للملتقى" },
      { src: "/assets/forum/D1205897.jpg", alt: "Attendee badge, Research Forum 2026", altAr: "تصميم بطاقة تعريف الحضور لملتقى البحث العلمي ٢٠٢٦" },
      { src: "/assets/forum/D1106323.jpg", alt: "Student project exhibition banners", altAr: "لوحات جدارية لعرض مشاريع الطلاب البحثية بالمعرض" },
      { src: "/assets/forum/D1205703.jpg", alt: "Forum entrance arch", altAr: "بوابة الدخول وواجهة الاستقبال الرئيسية للملتقى" },
      { src: "/assets/forum/D1106320.jpg", alt: "LED identity cube, close-up", altAr: "لقطة قريبة لمكعبات الهوية البصرية المضيئة الموزعة بالمقر" },
      { src: "/assets/forum/D1205739.jpg", alt: "Forum stage and presentation screen", altAr: "عرض المنصة وشاشات العرض الرئيسية والورش الجانبية" }
    ],
    nextProjectId: "wincom",
    prevProjectId: "graduation"
  },
  {
    id: "wincom",
    title: "WINCOM25 International Conference",
    titleAr: "المؤتمر الدولي WINCOM25",
    client: "Arab Open University × WINCOM",
    clientAr: "الجامعة العربية المفتوحة × وينكوم",
    year: "2025",
    role: "Event Visuals Designer",
    roleAr: "مصمم مرئيات الفعالية",
    duration: "1 Month",
    durationAr: "شهر واحد",
    coverImage: "/assets/wincom/WhatsApp Image 2026-07-12 at 1.36.13 AM.jpeg",
    brief: "WINCOM is an international, IEEE-affiliated conference on wireless networks and mobile communications. Its 2025 edition — the 12th overall — was hosted for the first time in Saudi Arabia, at Arab Open University in Riyadh, under the patronage of a member of the royal family, with international keynote speakers in attendance. AOU brought me in to design the event-facing visuals for the local hosting.",
    briefAr: "مؤتمر (WINCOM) هو مؤتمر دولي مصنف علمياً (IEEE) يعنى بشبكات الاتصال اللاسلكية والاتصالات المتنقلة. استضافت المملكة العربية السعودية النسخة الثانية عشرة منه لأول مرة بالجامعة العربية المفتوحة بالرياض، برعاية ملكية كريمة وبحضور متحدثين دوليين بارزين. استعانت بي الجامعة لتصميم المرئيات وشاشات العرض لهذه الاستضافة التاريخية الهامة.",
    approach: "This was my first project at this scale, and it set the direction for the two larger projects that followed it — the Research Forum and the Graduation Ceremony. I designed the event invitation and the supporting stage visuals, including the LCD cubes and the main stage screen.",
    approachAr: "مثّل هذا مشروع خطوتي الأولى لتصميم فعاليات بهذه الضخامة والمستوى الأكاديمي الدولي، ورسم لي خارطة الطريق والمنهجية للمشاريع الكبرى اللاحقة. تضمن عملي تصميم الدعوة الرسمية للمؤتمر والمرئيات المصاحبة للمسرح، بما في ذلك شاشات العرض ومكعبات الهوية البصرية المضيئة.",
    outcome: "No hard attendance numbers to report here, but the project itself mattered: it was the first time I worked at this scale, and it directly built the confidence and workflow I carried into the Research Forum and the Graduation Ceremony afterward.",
    outcomeAr: "رغم عدم وجود أرقام حضور دقيقة هنا، إلا أن نجاح هذا المشروع كان فاصلاً ومحورياً لي: كانت المرة الأولى التي أعمل فيها على فعاليات بهذا الحجم المرموق، وأكسبني الثقة العملية والخبرة والمنهجية التي بنيت عليها مشاريع الهوية للبحث العلمي وحفل التخرج الضخم بعدها.",
    tools: ["Affinity Designer", "Canva"],
    deliverables: [
      "Event invitation",
      "LCD cubes",
      "Main stage screen"
    ],
    deliverablesAr: [
      "دعوة حضور المؤتمر الرسمية",
      "المكعبات البصرية المضيئة",
      "شاشة خلفية المسرح الرئيسية"
    ],
    stats: [
      { value: "12th", valueAr: "١٢", label: "Conference Edition", labelAr: "نسخة المؤتمر" },
      { value: "1st", valueAr: "الأولى", label: "Saudi Hosted", labelAr: "استضافة سعودية" },
      { value: "3", valueAr: "٣", label: "Visual Deliverables", labelAr: "مخرجات بصرية رئيسية" },
      { value: "First", valueAr: "الأول", label: "Large-Scale Milestone", labelAr: "منعطف الفعاليات الكبرى" }
    ],
    images: [
      { src: "/assets/wincom/WhatsApp Image 2026-07-12 at 1.36.13 AM.jpeg", alt: "WINCOM25 main stage layout", altAr: "تصميم وتنفيذ الشاشة الرئيسية لخشبة مسرح مؤتمر وينكوم ٢٥" },
      { src: "/assets/wincom/WhatsApp Image 2026-07-12 at 1.36.14 AM.jpeg", alt: "WINCOM25 attendee registration & lobby", altAr: "منطقة تسجيل حضور مؤتمر وينكوم ٢٥ وصالة الاستقبال" },
      { src: "/assets/wincom/WhatsApp Image 2026-07-12 at 1.36.14 AM (1).jpeg", alt: "WINCOM25 session presentation", altAr: "عرض جلسات مؤتمر وينكوم ٢٥" },
      { src: "/assets/wincom/WhatsApp Image 2026-07-12 at 1.36.14 AM (2).jpeg", alt: "WINCOM25 exhibition hall & banners", altAr: "صالة المعرض المصاحب والمطبوعات الإرشادية لمؤتمر وينكوم ٢٥" }
    ],
    nextProjectId: "graduation",
    prevProjectId: "forum"
  }
];

export const GALLERY_ITEMS: GalleryItem[] = [
  { id: "g1", filename: "AOU (2).png", group: "aou", category: "events", label: "AOU promotional branding design", labelAr: "تصميم الهوية الترويجية للجامعة العربية المفتوحة" },
  { id: "g2", filename: "GPC  دعوة.png", group: "aou", category: "events", label: "Closing ceremony invitation layout", labelAr: "دعوة الحفل الختامي للأكاديمية والشركاء" },
  { id: "g3", filename: "AOU x foundation day.png", group: "aou", category: "awareness", label: "Founding Day celebratory poster", labelAr: "بوستر يوم التأسيس السعودي — الجامعة العربية المفتوحة" },
  { id: "g4", filename: "AOU foundation day (10).png", group: "aou", category: "awareness", label: "Founding Day digital illustration card", labelAr: "بطاقة توعوية بيوم التأسيس السعودي" },
  { id: "g5", filename: "women day - AOU (1).png", group: "aou", category: "awareness", label: "International Women's Day social graphic", labelAr: "البوستر التوعوي باليوم العالمي للمرأة" },
  { id: "g6", filename: "اليوم العالمي للانترنت 2026.png", group: "aou", category: "awareness", label: "Safer Internet Day awareness poster", labelAr: "بوستر اليوم العالمي للإنترنت الآمن 2026" },
  { id: "g7", filename: "اليوم العالمي للتراث.png", group: "aou", category: "awareness", label: "World Heritage Day cultural card", labelAr: "بطاقة اليوم العالمي للتراث الإنساني" },
  { id: "g8", filename: "اليوم العالمي للسرطان  AOU.png", group: "aou", category: "awareness", label: "World Cancer Awareness Day typography", labelAr: "البوستر التوعوي باليوم العالمي للسرطان" },
  { id: "g9", filename: "اليوم العالمي للقضاء على الهدر (3).png", group: "aou", category: "awareness", label: "Zero Waste Food Program announcement", labelAr: "البوستر التوعوي باليوم العالمي للحد من الهدر الغذائي" },
  { id: "g10", filename: "ايام عالمية.png", group: "aou", category: "awareness", label: "Global health observatory days layout A", labelAr: "سلسلة الأيام والأسابيع التوعوية العالمية — الجزء أ" },
  { id: "g11", filename: "ايام عالمية (1).png", group: "aou", category: "awareness", label: "Global health observatory days layout B", labelAr: "سلسلة الأيام والأسابيع التوعوية العالمية — الجزء ب" },
  { id: "g12", filename: "قائمة العميد.png", group: "aou", category: "events", label: "Dean's Honor List excellence announcement", labelAr: "تصميم إعلان قائمة العميد للمتميزين أكاديمياً" },
  { id: "g13", filename: "نسخة من اعلان القبول والتسجيل  AOU.png", group: "aou", category: "events", label: "New academic semester admissions campaign", labelAr: "تصميم حملة إعلان القبول والتسجيل للفصل الدراسي الجديد" },
  { id: "g14", filename: "نسخة سابقة مرقمة من  مجلة الجامعة  الإصدار الأول  2026.png", group: "aou", category: "events", label: "First issue university magazine editorial cover", labelAr: "غلاف مجلة الجامعة العربية المفتوحة — الإصدار الأول" },
  { id: "g15", filename: "اعلان اللغات.png", group: "clubs", category: "clubs", label: "WAMY scholarship booklet — Arabic edition", labelAr: "كتيب منحة الندوة العالمية للشباب الإسلامي — النسخة العربية", badge: "Localized · 6 Languages", badgeAr: "مترجم · ٦ لغات" },
  { id: "g16", filename: "world cup 26  AOU (3).png", group: "aou", category: "events", label: "World Cup qualifiers national support card", labelAr: "بوستر مؤازرة المنتخب الوطني في تصفيات كأس العالم" },
  { id: "g17", filename: "_الشيكات + اعلان الحفل الختامي.png", group: "aou", category: "events", label: "Academic competition winners' mock checks template A", labelAr: "تصاميم شيكات الفائزين بالمسابقات السنوية — الجزء أ" },
  { id: "g17_b", filename: "_الشيكات + اعلان الحفل الختامي (1).png", group: "aou", category: "events", label: "Academic competition winners' mock checks template B", labelAr: "تصاميم شيكات الفائزين بالمسابقات السنوية — الجزء ب" },
  { id: "g18", filename: "_الوعي الفكري ( تأكد وتحقق قبل أن تصدّق )  aou (3).png", group: "aou", category: "awareness", label: "Intellectual awareness & fact-checking campaign layout", labelAr: "حملة الوعي الفكري — 'تأكد وتحقق قبل أن تصدق'" },
  { id: "g19", filename: "الوعي الفكري (8).png", group: "aou", category: "awareness", label: "Digital literacy intellectual security layout", labelAr: "سلسلة منشورات الوعي الفكري والأمن الرقمي" },
  { id: "g20", filename: "_توعية تطعيم  aou.png", group: "aou", category: "awareness", label: "Seasonal vaccination drive community card", labelAr: "بوستر حملة التوعية بالتطعيمات الموسمية" },
  { id: "g21", filename: "ورشة.png", group: "aou", category: "events", label: "Professional training workshop card", labelAr: "تصميم إعلان ورشة العمل التفاعلية" },
  { id: "g22", filename: "ورشات ورش اخضر  aou.png", group: "aou", category: "events", label: "Green environment sustainability workshops series", labelAr: "تصاميم ورش العمل الخضراء للتنمية المستدامة" },
  { id: "g23", filename: "AI Club  Calender.png", group: "clubs", category: "clubs", label: "AI Student Club calendar template", labelAr: "التقويم الأكاديمي لنادي الذكاء الاصطناعي الطلابي" }
];
